runtime: nodejs
vm: true
env_variables: 
    BOT_TOKEN: '226053636:AAE1uPuboAxBiyIWEKybkwrVo5Z-vWXOnpw'
health_check:
    enable_health_check: true
    check_interval_sec: 5
    timeout_sec: 4
    unhealthy_threshold: 2
    healthy_threshold: 2
    restart_threshold: 60
skip_files:
- ^node_modules$